### ISSUE TITLE
Improving efficiency by setting hmmsearch --cpu 1 and running cath-genomescan.pl in parallel

### ISSUE THREAD

**Issue by alexdthomas** [UCLOrengoGroup/cath-tools-genomescan#12]
Hello, 

Thank you so much for cath-tools-genomescan, I've found it very useful so far.  

I was running `cath-genomscan.pl` on all of the genes predicted in my metagenome samples. It was taking quite a while, mostly due to `hmmsearch`, which despite the default behavior to use all available cpus usually only uses a few.  I wanted to figure out how to parallelize it and came up with this strategy. 

1) added an argument to `hmmsearch` in `cath-genomescan.pl` to only use 1 cpu (`'--cpu 1'`)
2) split my amino acid fasta files into the number of cpus I wanted to use (in this case 48)
3) wrote the `cath-genomescan.pl` commands for each of the sub files to a text file
4) submitted that text file to be run in parallel (cpus=48)

This seemed to work pretty well and got the results I was looking for very quickly.  I of course had to clean up some intermediate files and parse/aggregate the results into single files.  I figured I'd share the strategy.  Not sure how easily it can be implemented for `cath-genomescan.pl`, but at least providing an argument to set the number of cpus used by `hmmsearch` could be helpful.  

Here is the nasty bash code I used inside a loop over my directories.  Tried to clean up a little to make it easier to read.
```
#get the headers from the faa file 
      grep "^>" min1000_faa > min1000_faa_headers.txt
#split into 48 chunks
      split --number=l/48 min1000_faa_headers.txt --additional-suffix=_headers_split
#remove the leading ">" from the headers 
      sed -i 's/>//g' *_headers_split
#for each of the header chunks 
      for i in *_headers_split;
      do
#use pullseq to get the aa sequences for each chunk (https://github.com/bcthomas/pullseq)
        pullseq -i $min1000_faa -n $i > $i.faa
#append the cath-genomescan.pl command for that chunk to a text file
        echo "/path/to/cath-tools-genomescan/apps/cath-genomescan.pl -i $PWD/$i.faa -l path/to/cath-tools-genomescan/data/funfam-hmm3.lib -o $PWD/$i.faa.out" >> cath_genomescan_cluster_commands.txt
      done
#now send the cath-genomescan.pl commands to parallel with 48 cpus and pipe to qsub to submit to the cluster 
echo "parallel -j48 < $PWD/cath_genomescan_cluster_commands.txt" | qsub -V -N cath_${sample}
```

Cheers, 
Alex

**Comment by sillitoe** [comment]
Hi Alex,

Great - glad the code is useful and thanks very much for the suggestion - I'm sure this strategy would be useful to others.

I'm currently thinking it might be best to add this as extra documentation in the Wiki area - would you be okay with that?

Best,

Ian

**Comment by alexdthomas** [comment]
Hi Ian, 

I'd be fine with you adding this to the Wiki area, happy to make a contribution.  

It might be worth adding a warning about `GNU parallel`.  I only recently started using it and the postdoc who showed it to me emphasized how useful it is, but also how easy it is to 'bad things'.  Users should be aware of how many CPUs are available and how many they can use (specified by the `-j` argument).  In my example I was submitting my command to a cluster node (via ` | qsub`) with 48 CPUs and our system is set up so only one user is on a node at a time, so I could use all 48.  If I had run it on our head node our lab policy is users should only use 6 CPUs, so I could have prevented the rest of the lab from getting any work done and possibly crashed our server (I think) if I had used 48...

Cheers, 
Alex

**Comment by sillitoe** [comment]
Great - thanks.

I've added this in the Wiki section with a suitable warning/disclaimer. I've also added a GPL v3 license to the project which will cover any code in this section too.

https://github.com/UCLOrengoGroup/cath-tools-genomescan/wiki

Thanks very much for your contribution.
