### ISSUE TITLE
retrieve_FunFam_aln_GO_anno_CATH-API.pl: No such file or directory

### ISSUE THREAD

**Issue by alexdthomas** [UCLOrengoGroup/cath-tools-genomescan#13]
Hello again, 

Following the example here (https://github.com/UCLOrengoGroup/cath-tools-genomescan) to get the EC numbers and GO terms for a CATH FunFam model. With the test data, when I run `./apps/retrieve_FunFam_aln_GO_anno_CATH-API.pl 2.40.50.140/FF/58874 v4_1_0` in my project directory I get the following error `-bash: ./apps/retrieve_FunFam_aln_GO_anno_CATH-API.pl: No such file or directory`. 

Looking at `retrieve_FunFam_aln_GO_anno_CATH-API.pl` this makes sense, since on line 34 it seems to have a 'results' directory hardcoded to be in the parent directory of the current directory.  It also seems to be looking for `*.sto.aln` and `*.GO.anno` files there that I can't figure out where they would have been produced.  

On line 42 it does seem to construct a correct url to download the stockholm alignment file for the given FunFam and this file does contain the EC and GO metadata (as well as other useful information).  

As I have run `cath-genomescan.pl` on all of the proteins predicted in my metagenome, it seemed very inefficient for me and the CATH API server to query the server for the redundant set of CATH FunFams, so I generated a non-redundant list and downloaded all of the stockholm files for those.  I've been working on parsing out the metadata I am interested in, but keep hitting little text formatting and things I wasn't expecting...

Maybe I'm just incapable of finding it, but Is here is a table somewhere on the FTP (ftp://orengoftp.biochem.ucl.ac.uk/cath/releases/latest-release/) that has the CATH superfamily IDs, FunFam IDs, and associated ECs and GOs (maybe even accessions, definitions, descriptions, but that could be a bit much...)?  It would be really useful for users and might save some unnecessary traffic downloading thousands of alignments just to get the metadata.  I noticed in several publications (DOI 10.1093/nar/gkv488, 10.1093/bioinformatics/btv398) that the ability to connect FunFams to ECs is a feature of the FunFams, I've just had a hard time doing it efficiently and programmatically.  

Thanks, 
Alex

**Comment by sayonidas03** [comment]
Hi Alex,

Thanks a lot for reporting this. I have removed the hard-coded results/
path and updated the script to also generate an EC annotation file as well.
The README has also been updated accordingly.
Please let us know if you are able to get the EC information for the
FunFams using the script.

In the current release, only the FunFam stockholm alignments capture the GO
and EC annotations from UniProtKB for all its relatives (uniprot ids, pdb
ids) during the time of release.

Kind Regards,

Sayoni

**Comment by alexdthomas** [comment]
Hi Sayoni, 

Thank you for your prompt response.  

I can confirm the updated `retrieve_FunFam_aln_GO_EC_anno_CATH-API.pl` works as described.  I also feel like commending you for writing a perl script I can actually read (I don't write in perl myself and it usually looks like a jumble of metacharacters to me).  

Thanks for confirming the stockholm alignments are the only files that contain the EC and GO annotations linked to FunFams.  Glad downloading and parsing them hasn't been a waste of my time.  If I could put in a feature request for a table with that information in the next release I still think that would be helpful.  

Cheers, 
Alex

**Comment by sillitoe** [comment]
Thanks for raising this issue. I'm closing this, but have opened a new ticket for the GO/EC data request.

https://github.com/UCLOrengoGroup/cath-todo/issues/41
