### ISSUE TITLE
get cath-resolve-hits compiling on Mac

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools-genomescan#7]

**Comment by tonyelewis** [comment]
I've added MacOS to the [Travis-CI builds](https://travis-ci.org/UCLOrengoGroup/cath-tools) for [UCLOrengoGroup/cath-tools](https://github.com/UCLOrengoGroup/cath-tools) so there should generally be MacOS executables in cath-tools releases from now on.

I've created release [v0.14.2](https://github.com/UCLOrengoGroup/cath-tools/releases/tag/v0.14.2) to mark this wondrous happening.

Does that satisfy this issue?

**Comment by sillitoe** [comment]
thanks Tony
